# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args:
          - --fix

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
        exclude: 'tests/fixtures/dag_factory.yml|dev/dags/invalid.yaml|tests/fixtures/invalid_yaml.yml'
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args: [ "--autofix" ]
      - id: trailing-whitespace
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [ "--allow-missing-credentials" ]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.3
    hooks:
      - id: uv-lock

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: [ "--config", "./pyproject.toml" ]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        exclude: 'tests/fixtures/mydocfile\.md|uv\.lock'

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args:
          - "--disable=MD013"  # disable line length
          - "--disable=MD024"  # disable multiple headings with the same content (CHANGELOG)
          - "--disable=MD033"  # disable no inline html (needed for analytics dead pixel)

  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.13.6
    hooks:
      - id: markdown-link-check
        args: [-q]
