import copy
import datetime as _dt
import inspect
import re
import textwrap

from dagfactory.dagbuilder import AIRFLOW3_MAJOR_VERSION, INSTALLED_AIRFLOW_VERSION, DagBuilder, import_string
from dagfactory.utils import get_datetime, get_python_callable, get_python_callable_lambda, parse_list_datasets


def indent_block(text: str, levels: int = 1) -> str:
    """Shift every line of a self-relative code block (flush-left, internally consistent)
    by `levels` nesting levels, so it can be embedded at any depth (DAG > task_group > task_group > task)."""
    return textwrap.indent(text, "    " * levels)


class _RawCode(str):
    """Marker for a value that is already valid Python source and must be emitted verbatim."""


def generate_dags_file(dags: dict[str, dict]) -> str:
    """Generate a single Python file containing multiple DAGs."""
    imports = {"from airflow import DAG"}
    dag_blocks = []

    for dag_name, dag_config in dags.items():
        block, dag_imports = generate_dag_block(dag_name, dag_config)
        imports.update(dag_imports)
        dag_blocks.append(block)

    imports_str = "\n".join(sorted(imports))
    dags_str = "\n\n\n".join(dag_blocks)

    return f"""# Generated by dagfactory codegen — do not edit manually
{imports_str}


{dags_str}
"""


DATETIME_PARAMS = {"start_date", "end_date"}

CALLBACK_TYPES = [
    "on_execute_callback",
    "on_success_callback",
    "on_failure_callback",
    "on_retry_callback",
    "on_skipped_callback",
    "sla_miss_callback",
]
# Keys whose value, when given as a "module.attr" string, must be imported and referenced
# directly (matching dagbuilder's `import_string` behavior) rather than kept as a str literal.
CALLABLE_STRING_KEYS = set(CALLBACK_TYPES) | {"python_callable", "execution_date_fn"}
# Keys resolved via a `<base>_name` + `<base>_file` pair, matching dagbuilder's `get_python_callable`.
NAME_FILE_BASE_KEYS = CALLBACK_TYPES + ["execution_date_fn", "python_callable"]


def resolve_name_file_callables(config: dict, imports: set) -> None:
    """Mutate `config` in place, replacing `<base>_name`/`<base>_file` pairs with a resolved callable."""
    for base in NAME_FILE_BASE_KEYS:
        name_key, file_key = f"{base}_name", f"{base}_file"
        if name_key in config and file_key in config:
            imports.add("from dagfactory.utils import get_python_callable")
            name_val = config.pop(name_key)
            file_val = config.pop(file_key)
            config[base] = _RawCode(f"get_python_callable({name_val!r}, {file_val!r})")


# HTTP sensor's `response_check`, and SqlSensor's `success`/`failure`: unlike `resolve_name_file_callables`,
# the output key doesn't always match the input `<prefix>_name`/`<prefix>_file`/`<prefix>_lambda` keys.
SENSOR_CALLABLE_PAIRS = {
    "response_check": "response_check",
    "success": "success_check",
    "failure": "failure_check",
}


def resolve_callable_pairs(config: dict, imports: set, pairs: dict) -> None:
    """Mutate `config` in place. For each `output_key: input_prefix` pair, resolve
    `<prefix>_name`+`<prefix>_file` (via `get_python_callable`) or `<prefix>_lambda` (via
    `get_python_callable_lambda`) into `config[output_key]`, matching dagbuilder's per-operator
    special-casing for HTTP/SQL sensors."""
    for output_key, prefix in pairs.items():
        name_key, file_key, lambda_key = f"{prefix}_name", f"{prefix}_file", f"{prefix}_lambda"
        if name_key in config and file_key in config:
            imports.add("from dagfactory.utils import get_python_callable")
            name_val = config.pop(name_key)
            file_val = config.pop(file_key)
            config[output_key] = _RawCode(f"get_python_callable({name_val!r}, {file_val!r})")
        elif lambda_key in config:
            imports.add("from dagfactory.utils import get_python_callable_lambda")
            lambda_val = config.pop(lambda_key)
            config[output_key] = _RawCode(f"get_python_callable_lambda({lambda_val!r})")


def resolve_variables_as_arguments(config: dict, imports: set) -> None:
    """Mutate `config` in place: for each {variable, attribute} pair in 'variables_as_arguments',
    set config[attribute] to a `Variable.get(...)` call. This is deliberately NOT resolved eagerly
    at generation time — Airflow Variables live in the metadata DB, not an importable module, so
    (matching dagbuilder) the value must be read fresh at DAG-parse time by the generated code."""
    variables = config.pop("variables_as_arguments", None)
    if not variables:
        return
    imports.add(
        "try:\n    from airflow.sdk.definitions.variable import Variable\nexcept ImportError:\n"
        "    from airflow.models import Variable"
    )
    default_kwarg = "default_var" if INSTALLED_AIRFLOW_VERSION.major < AIRFLOW3_MAJOR_VERSION else "default"
    for variable in variables:
        var_name = variable["variable"]
        attr = variable["attribute"]
        config[attr] = _RawCode(f"Variable.get({var_name!r}, {default_kwarg}=None)")


def resolve_dataset_schedule(schedule: dict) -> _RawCode:
    """Render a `schedule: {datasets: ..., file: ...}` dict by delegating to DagBuilder's own
    dataset-condition resolution, instead of re-implementing its boolean-expression parsing here."""
    datasets = schedule["datasets"]
    condition = parse_list_datasets(datasets)
    if "file" in schedule:
        return _RawCode(f"DagBuilder.process_file_with_datasets({schedule['file']!r}, {condition!r})")
    return _RawCode(f"DagBuilder.evaluate_condition_with_datasets({condition!r})")


def sanitize_identifier(name: str) -> str:
    """Turn a task_id (which may contain characters invalid in a Python identifier) into a safe
    variable name for the generated source. The original task_id is preserved via `task_id=`."""
    ident = re.sub(r"\W", "_", str(name))
    if not ident or ident[0].isdigit():
        ident = f"_{ident}"
    return ident


def render_value(value, imports: set) -> str:
    """Render a Python value (as loaded from YAML, with `__type__` dicts left intact) as source code."""
    if isinstance(value, _RawCode):
        return str(value)
    if isinstance(value, (_dt.datetime, _dt.date)):
        imports.add("import pendulum")
        return f'pendulum.parse("{get_datetime(value).isoformat()}")'
    if isinstance(value, dict):
        if value.get("__type__") == "builtins.list" and "items" in value:
            items = ", ".join(render_value(item, imports) for item in value["items"])
            return f"[{items}]"
        if "__type__" in value:
            module, class_name = value["__type__"].rsplit(".", 1)
            imports.add(f"from {module} import {class_name}")
            args_code = [render_value(arg, imports) for arg in value.get("__args__", [])]
            kwargs_code = [
                f"{k}={render_value(v, imports)}" for k, v in value.items() if k not in ("__type__", "__args__")
            ]
            return f"{class_name}({', '.join(args_code + kwargs_code)})"
        items = ", ".join(f"{k!r}: {render_value(v, imports)}" for k, v in value.items())
        return "{" + items + "}"
    if isinstance(value, list):
        return "[" + ", ".join(render_value(v, imports) for v in value) + "]"
    return repr(value)


def resolve_callback_dict(callback_dict: dict, imports: set) -> str:
    """Render a dict-form callback (`{callback: 'module.Class', **kwargs}`), matching dagbuilder's
    `set_callback` exactly: a Notifier class (has `.notify`) is instantiated directly with the
    kwargs, otherwise the callable is wrapped as `functools.partial(fn, **kwargs)` — never left
    as a raw dict, which Airflow would accept at DAG-parse time but fail to actually call later."""
    callback_path = callback_dict["callback"]
    module, cls_name = callback_path.rsplit(".", 1)
    imports.add(f"from {module} import {cls_name}")
    rest = {k: v for k, v in callback_dict.items() if k != "callback"}
    kwargs_str = ", ".join(f"{k}={render_value(v, imports)}" for k, v in rest.items())

    try:
        is_notifier = hasattr(import_string(callback_path), "notify")
    except Exception:
        is_notifier = False

    if is_notifier:
        return f"{cls_name}({kwargs_str})"
    imports.add("from functools import partial")
    return f"partial({cls_name}, {kwargs_str})"


def format_value(key: str, value, imports: set) -> str:
    """Render a single value as source code, special-casing dates and importable callables."""
    if isinstance(value, _RawCode):
        return str(value)
    if (
        key in CALLBACK_TYPES
        and isinstance(value, dict)
        and isinstance(value.get("callback"), str)
    ):
        return resolve_callback_dict(value, imports)
    if key in CALLABLE_STRING_KEYS and isinstance(value, str) and "." in value:
        module, attr = value.rsplit(".", 1)
        imports.add(f"from {module} import {attr}")
        return attr
    if key in DATETIME_PARAMS and isinstance(value, str):
        imports.add("import pendulum")
        return f'pendulum.parse("{get_datetime(value).isoformat()}")'
    return render_value(value, imports)


# Matches dagbuilder's `_replace_kwargs_values_as_xcom` exactly: '+task' or the
# multiple_outputs=True form '+task["xcom_key"]'.
TASKFLOW_XCOM_REF_PATTERN = re.compile(r"^\+(?P<task>\w*)(\[['\"](?P<xcom_key>.*)['\"]\])?$")


def resolve_taskflow_value(key: str, value, imports: set) -> str:
    """Render a TaskFlow callable-kwarg value. A string prefixed with '+' references another
    task's output directly (e.g. '+some_number' -> the Python variable `some_number`, or
    '+collect[\"key1\"]' -> `collect['key1']` for a multiple_outputs=True task), matching
    dagbuilder's `+task_name` XComArg-reference convention."""
    if isinstance(value, str) and value.startswith("+"):
        match = TASKFLOW_XCOM_REF_PATTERN.match(value)
        if match:
            var_name = sanitize_identifier(match.group("task"))
            xcom_key = match.group("xcom_key")
            return f"{var_name}[{xcom_key!r}]" if xcom_key else var_name
        return sanitize_identifier(value[1:])
    return format_value(key, value, imports)


def resolve_expand_value(key: str, value, imports: set) -> str:
    """Render an `expand`/`partial` kwarg value for a regular (non-decorator) mapped task.
    A string containing '.output' or 'XcomArg(...)' references another task's mapped output —
    both resolve to the same `{task_id}.output` XComArg attribute, matching dagbuilder's
    `replace_expand_values` convention."""
    if isinstance(value, str):
        if ".output" in value:
            task_id = value.split(".output")[0]
            return f"{sanitize_identifier(task_id)}.output"
        if "XcomArg" in value:
            task_id = re.findall(r"\(+(.*?)\)", value)[0]
            return f"{sanitize_identifier(task_id)}.output"
    return format_value(key, value, imports)


def format_param(key: str, value, imports: set) -> str:
    """Render a single `key=value` constructor argument as source code."""
    return f"{key}={format_value(key, value, imports)}"


def format_default_args(default_args: dict, imports: set) -> str:
    """Render a default_args dict as source code, preserving datetime handling per key."""
    items = ", ".join(f"{key!r}: {format_value(key, value, imports)}" for key, value in default_args.items())
    return "{" + items + "}"


DOC_MD_PARAMS = {"doc_md_file_path", "doc_md_python_callable_name", "doc_md_python_callable_file", "doc_md_python_arguments"}


def generate_doc_md_statements(dag_name: str, var_name: str, dag_config: dict, imports: set) -> list:
    """Render post-construction `dag.doc_md = ...` statements. Unlike plain `doc_md` (a normal
    DAG() kwarg), `doc_md_file_path` and `doc_md_python_callable_*` are NOT constructor kwargs —
    dagbuilder sets them on the DAG object after building it, so passing them to DAG() directly
    would raise a TypeError at generation/import time."""
    statements = []

    file_path = dag_config.get("doc_md_file_path")
    if file_path:
        statements.append(f'{var_name}.doc_md = open({file_path!r}, encoding="utf-8").read()')

    callable_name = dag_config.get("doc_md_python_callable_name")
    callable_file = dag_config.get("doc_md_python_callable_file")
    if callable_name and callable_file:
        imports.add("from dagfactory.utils import get_python_callable")
        args = dag_config.get("doc_md_python_arguments", {})
        args_str = render_value(args, imports)
        statements.append(
            f"{var_name}.doc_md = get_python_callable({callable_name!r}, {callable_file!r})(**{args_str})"
        )

    return statements


def generate_dag_block(dag_name: str, dag_config: dict) -> tuple[str, set]:
    """Generate a single DAG block and return it with its required imports."""
    dag_config = copy.deepcopy(dag_config)

    task_groups = DagBuilder._normalise_task_groups_config(dag_config.get("task_groups"))
    if "schedule_interval" in dag_config:
        raise ValueError("The `schedule_interval` key is no longer supported in Airflow 3.0+. Use `schedule` instead.")

    tasks = dag_config.get("tasks", {})
    if isinstance(tasks, list):
        tasks = {task["task_id"]: {k: v for k, v in task.items() if k != "task_id"} for task in tasks}

    imports = set()

    resolve_name_file_callables(dag_config, imports)
    # DAG() has no `on_execute_callback`/`on_retry_callback`/`on_skipped_callback` params — dagbuilder
    # resolves them too but never forwards them to the DAG constructor (only default_args propagates them).
    for invalid_dag_level_callback in ("on_execute_callback", "on_retry_callback", "on_skipped_callback"):
        dag_config.pop(invalid_dag_level_callback, None)

    default_args = dag_config.get("default_args", {})
    resolve_name_file_callables(default_args, imports)

    for task_config in tasks.values():
        if not task_config.get("operator") and not task_config.get("decorator"):
            raise ValueError("Tasks must define either 'operator' or 'decorator'")
        if task_config.get("operator"):
            imports.add(get_operator_import(task_config["operator"]))
        resolve_name_file_callables(task_config, imports)
        resolve_callable_pairs(task_config, imports, SENSOR_CALLABLE_PAIRS)
        resolve_variables_as_arguments(task_config, imports)

    nodes, roots = build_task_group_tree(task_groups)
    group_names = frozenset(nodes)

    tasks_by_group: dict[str, dict] = {}
    top_level_tasks: dict[str, dict] = {}
    for task_name, task_config in tasks.items():
        group_name = task_config.get("task_group_name")
        if group_name:
            tasks_by_group.setdefault(group_name, {})[task_name] = task_config
        else:
            top_level_tasks[task_name] = task_config

    tasks_code = []
    for task_name in order_tasks_by_reference(top_level_tasks):
        tasks_code.append(indent_block(generate_task_code(task_name, top_level_tasks[task_name], imports)))
    for group_name in roots:
        tasks_code.append(indent_block(render_task_group_block(group_name, nodes, tasks_by_group, imports)))

    dependencies_code = generate_dependencies_code(tasks, group_names)
    group_dependencies_code = generate_group_dependencies_code(nodes, group_names)
    for code in (dependencies_code, group_dependencies_code):
        if code:
            tasks_code.append(indent_block(code))

    tasks_str = "\n\n".join(tasks_code)

    dag_params = [f"dag_id={dag_name!r}"]
    if default_args:
        dag_params.append(f"default_args={format_default_args(default_args, imports)}")
    skip_keys = {"tasks", "task_groups", "default_args"} | DOC_MD_PARAMS
    for key, value in dag_config.items():
        if key in skip_keys:
            continue
        if key == "schedule" and isinstance(value, list) and all(isinstance(v, str) for v in value):
            imports.add("from airflow.sdk import Asset")
            assets_str = ", ".join(f"Asset({v!r})" for v in value)
            dag_params.append(f"schedule=[{assets_str}]")
        elif key == "schedule" and isinstance(value, dict) and "datasets" in value:
            imports.add("from dagfactory.dagbuilder import DagBuilder")
            dag_params.append(f"schedule={resolve_dataset_schedule(value)}")
        else:
            dag_params.append(format_param(key, value, imports))

    dag_params_str = ",\n    ".join(dag_params)
    var_name = f"dag_{sanitize_identifier(dag_name)}"

    doc_md_lines = generate_doc_md_statements(dag_name, var_name, dag_config, imports)
    doc_md_str = ("\n" + "\n".join(doc_md_lines) + "\n") if doc_md_lines else "\n"

    block = f"""# dag_id: {dag_name}
{var_name} = DAG(
    {dag_params_str},
){doc_md_str}with {var_name}:
{tasks_str}"""

    return block, imports

def build_task_group_tree(task_groups: dict) -> tuple[dict, list[str]]:
    """Resolve `parent_group_name` into a tree of nodes, keyed by group name.

    Returns (nodes, roots) where nodes[name] = {"conf", "children_groups", "parent"}.
    Raises ValueError on an unknown parent_group_name or a circular parent chain.
    """
    nodes = {}
    for name, conf in task_groups.items():
        nodes[name] = {"conf": conf, "children_groups": [], "parent": conf.get("parent_group_name")}

    for name, node in nodes.items():
        parent = node["parent"]
        if parent is not None:
            if parent not in nodes:
                raise ValueError(f"task_group '{name}' references unknown parent_group_name '{parent}'")
            nodes[parent]["children_groups"].append(name)

    for name in nodes:
        seen = []
        current = name
        while nodes[current]["parent"] is not None:
            current = nodes[current]["parent"]
            if current in seen:
                raise ValueError(f"Circular parent_group_name dependency detected involving '{name}'")
            seen.append(current)

    roots = [name for name, node in nodes.items() if node["parent"] is None]
    return nodes, roots


def _var_name_for(name: str, group_names: frozenset) -> str:
    """A task_group and a task can share the 'dependencies' namespace (either can depend on
    the other); prefix group variable names so they can never collide with a task's."""
    if name in group_names:
        return f"tg_{sanitize_identifier(name)}"
    return sanitize_identifier(name)


def extract_inline_task_refs(task_config: dict) -> set:
    """Find task names referenced inline via a TaskFlow '+name' value or an expand '.output'/
    'XcomArg(...)' value. Unlike 'dependencies' (resolved via trailing '>>' statements, so order
    doesn't matter), these are evaluated as part of the task's own line, so the referenced task's
    Python variable must already be defined earlier in the generated source."""
    refs = set()

    def scan(value):
        if isinstance(value, str):
            if value.startswith("+"):
                refs.add(value[1:])
            elif ".output" in value:
                refs.add(value.split(".output")[0])
            elif "XcomArg" in value:
                match = re.findall(r"\(+(.*?)\)", value)
                if match:
                    refs.add(match[0])
        elif isinstance(value, dict):
            for nested in value.values():
                scan(nested)

    for key, value in task_config.items():
        if key in TASK_SYSTEM_PARAMS or key == "python_callable":
            continue
        scan(value)
    return refs


def order_tasks_by_reference(tasks: dict) -> list:
    """Order tasks so any task referenced inline by another (see `extract_inline_task_refs`)
    is emitted first, while otherwise preserving the original order as much as possible."""
    refs = {name: extract_inline_task_refs(conf) & set(tasks) for name, conf in tasks.items()}
    ordered = []
    visited = set()

    def visit(name, trail):
        if name in visited or name in trail:
            return
        trail.add(name)
        for ref in refs.get(name, ()):
            visit(ref, trail)
        visited.add(name)
        ordered.append(name)

    for name in tasks:
        visit(name, set())
    return ordered


def generate_dependencies_code(tasks: dict, group_names: frozenset = frozenset()) -> str:
    """Generate '>>' dependency statements from each task's 'dependencies' list."""
    lines = []
    for task_name, task_config in tasks.items():
        for upstream in task_config.get("dependencies", []):
            lines.append(f"{_var_name_for(upstream, group_names)} >> {_var_name_for(task_name, group_names)}")
    return "\n".join(lines)


def generate_group_dependencies_code(nodes: dict, group_names: frozenset) -> str:
    """Generate '>>' statements from each task_group's own 'dependencies' list."""
    lines = []
    for name, node in nodes.items():
        for upstream in node["conf"].get("dependencies", []):
            lines.append(f"{_var_name_for(upstream, group_names)} >> {_var_name_for(name, group_names)}")
    return "\n".join(lines)


GROUP_SYSTEM_PARAMS = {"parent_group_name", "dependencies"}


def render_task_group_block(name: str, nodes: dict, tasks_by_group: dict, imports: set) -> str:
    """Recursively render one task_group — and any tasks/nested groups it contains — as a
    `with TaskGroup(...):` block. Nesting `with` blocks makes Airflow resolve parent_group on
    its own, so no explicit `parent_group=` kwarg is needed."""
    imports.add("from airflow.sdk import TaskGroup")
    node = nodes[name]
    conf = node["conf"]

    group_default_args = conf.get("default_args")
    if isinstance(group_default_args, dict):
        resolve_name_file_callables(group_default_args, imports)

    params = [f"group_id={name!r}"]
    for key, value in conf.items():
        if key in GROUP_SYSTEM_PARAMS:
            continue
        params.append(format_param(key, value, imports))
    params_str = ", ".join(params)

    group_tasks = tasks_by_group.get(name, {})
    body_blocks = []
    for task_name in order_tasks_by_reference(group_tasks):
        body_blocks.append(indent_block(generate_task_code(task_name, group_tasks[task_name], imports)))
    for child_name in node["children_groups"]:
        body_blocks.append(indent_block(render_task_group_block(child_name, nodes, tasks_by_group, imports)))

    body = "\n\n".join(body_blocks) if body_blocks else "    pass"
    var_name = _var_name_for(name, frozenset(nodes))
    return f"with TaskGroup({params_str}) as {var_name}:\n{body}"


def get_operator_import(operator_str: str) -> str:
    if "." not in operator_str:
        raise ValueError(
            f"Invalid operator '{operator_str}' must be a full path like 'airflow.operators.bash.BashOperator'"
        )
    module, class_name = operator_str.rsplit(".", 1)
    return f"from {module} import {class_name}"


TASK_SYSTEM_PARAMS = {"operator", "decorator", "dependencies", "task_group_name", "parent_group_name"}


def generate_task_code(task_name: str, task_config: dict, imports: set | None = None) -> str:
    if imports is None:
        imports = set()

    if task_config.get("decorator"):
        return generate_taskflow_task_code(task_name, task_config, imports)

    if task_config.get("expand"):
        return generate_mapped_task_code(task_name, task_config, imports)

    entry_point = task_config.get("operator")
    _, class_name = entry_point.rsplit(".", 1)

    params = [f"task_id={task_name!r}"]
    for key, value in task_config.items():
        if key not in TASK_SYSTEM_PARAMS:
            params.append(format_param(key, value, imports))

    params_str = ",\n    ".join(params)
    var_name = sanitize_identifier(task_name)
    return f"{var_name} = {class_name}(\n    {params_str},\n)"


TASKFLOW_SYSTEM_PARAMS = TASK_SYSTEM_PARAMS | {"python_callable"}
# Fallback only: used when the callable can't be imported at generation time (see
# `get_callable_arg_names`) and we can't tell decorator-level kwargs from callable args by
# introspection. When introspection succeeds, ANY kwarg not in the callable's own signature
# is treated as decorator-level — matching dagbuilder's `inspect.getfullargspec` routing exactly.
TASKFLOW_DECORATOR_KWARGS = {"map_index_template", "multiple_outputs"}


def get_callable_arg_names(task_config: dict) -> set | None:
    """Import the real python_callable (matching how dagbuilder resolves it) to introspect its
    parameter names, so kwargs can be routed to the decorator vs. the wrapped call exactly like
    dagbuilder's `make_decorator` does. Returns None if the callable can't be resolved this way
    (e.g. its module isn't importable at generation time) — callers then fall back to
    `TASKFLOW_DECORATOR_KWARGS`, a small set of known decorator-only kwargs."""
    try:
        if "python_callable_name" in task_config and "python_callable_file" in task_config:
            fn = get_python_callable(task_config["python_callable_name"], task_config["python_callable_file"])
        elif isinstance(task_config.get("python_callable"), str) and not isinstance(
            task_config["python_callable"], _RawCode
        ):
            fn = import_string(task_config["python_callable"])
        else:
            return None
        return set(inspect.getfullargspec(fn).args)
    except Exception:
        return None


def _is_decorator_kwarg(key: str, callable_arg_names) -> bool:
    """Whether a TaskFlow task_config key belongs in the `task(...)` call (vs. the wrapped
    function call), matching dagbuilder's inspect-based routing when possible."""
    if callable_arg_names is not None:
        return key not in callable_arg_names
    return key in TASKFLOW_DECORATOR_KWARGS


def _taskflow_decorator_call(
    task_name: str, decorator_name: str, callable_value: str, task_config: dict, decorator_keys, imports: set
) -> str:
    """Build the `decorator_name(task_id=..., python_callable=..., ...)` first call, including
    any decorator-level kwargs (e.g. map_index_template, or retries when it isn't a callable arg)."""
    parts = [f"task_id={task_name!r}", f"python_callable={callable_value}"]
    for key in decorator_keys:
        parts.append(f"{key}={format_value(key, task_config[key], imports)}")
    return f"{decorator_name}({', '.join(parts)})"


def generate_taskflow_task_code(task_name: str, task_config: dict, imports: set) -> str:
    """Render a TaskFlow (`decorator`) task as `task(python_callable=fn)(kwargs...)`, matching
    how dagbuilder's `make_decorator` wraps an existing callable rather than defining `@task def ...`."""
    callable_arg_names = get_callable_arg_names(task_config)
    resolve_name_file_callables(task_config, imports)

    if task_config.get("expand"):
        return generate_taskflow_mapped_task_code(task_name, task_config, imports, callable_arg_names)

    decorator_path = task_config["decorator"]
    module, decorator_name = decorator_path.rsplit(".", 1)
    imports.add(f"from {module} import {decorator_name}")

    callable_value = format_value("python_callable", task_config["python_callable"], imports)

    other_keys = [key for key in task_config if key not in TASKFLOW_SYSTEM_PARAMS]
    decorator_keys = [key for key in other_keys if _is_decorator_kwarg(key, callable_arg_names)]
    callable_keys = [key for key in other_keys if key not in decorator_keys]

    callable_kwargs = [f"{key}={resolve_taskflow_value(key, task_config[key], imports)}" for key in callable_keys]
    kwargs_str = ", ".join(callable_kwargs)

    var_name = sanitize_identifier(task_name)
    decorator_call = _taskflow_decorator_call(
        task_name, decorator_name, callable_value, task_config, decorator_keys, imports
    )
    return f"{var_name} = {decorator_call}({kwargs_str})"


def generate_taskflow_mapped_task_code(
    task_name: str, task_config: dict, imports: set, callable_arg_names=None
) -> str:
    """Render a TaskFlow task using dynamic task mapping as
    `task(task_id=..., python_callable=fn).partial(...).expand(...)`, matching `make_decorator`."""
    decorator_path = task_config["decorator"]
    module, decorator_name = decorator_path.rsplit(".", 1)
    imports.add(f"from {module} import {decorator_name}")

    callable_value = format_value("python_callable", task_config["python_callable"], imports)
    expand_conf = task_config["expand"]
    partial_conf = task_config.get("partial", {})

    other_keys = [
        key for key in task_config if key not in TASKFLOW_SYSTEM_PARAMS and key not in ("expand", "partial")
    ]
    # dagbuilder only rejects a leftover key when it actually matches the callable's own
    # signature (i.e. it should have been under expand/partial instead) — a genuine
    # decorator-level kwarg like `retries` or `map_index_template` is fine alongside mapping.
    misplaced_callable_args = [key for key in other_keys if not _is_decorator_kwarg(key, callable_arg_names)]
    if misplaced_callable_args:
        raise ValueError(
            "When using dynamic task mapping, all the task arguments should be defined in expand and partial."
        )

    var_name = sanitize_identifier(task_name)
    call = _taskflow_decorator_call(task_name, decorator_name, callable_value, task_config, other_keys, imports)

    if partial_conf:
        partial_params = ", ".join(
            f"{key}={resolve_taskflow_value(key, value, imports)}" for key, value in partial_conf.items()
        )
        call += f".partial({partial_params})"

    expand_params = ", ".join(
        f"{key}={resolve_taskflow_value(key, value, imports)}" for key, value in expand_conf.items()
    )
    call += f".expand({expand_params})"

    return f"{var_name} = {call}"


def generate_mapped_task_code(task_name: str, task_config: dict, imports: set) -> str:
    """Render a regular (non-decorator) operator using dynamic task mapping as
    `Operator.partial(static_kwargs).expand(mapped_kwargs)`, matching dagbuilder's `make_task`."""
    entry_point = task_config["operator"]
    _, class_name = entry_point.rsplit(".", 1)

    expand_conf = task_config["expand"]
    partial_conf = task_config.get("partial", {})

    partial_params = [f"task_id={task_name!r}"]
    for key, value in task_config.items():
        if key in TASK_SYSTEM_PARAMS or key in ("expand", "partial"):
            continue
        partial_params.append(format_param(key, value, imports))
    for key, value in partial_conf.items():
        partial_params.append(format_param(key, value, imports))
    partial_params_str = ",\n    ".join(partial_params)

    expand_params = [f"{key}={resolve_expand_value(key, value, imports)}" for key, value in expand_conf.items()]
    expand_params_str = ",\n    ".join(expand_params)

    var_name = sanitize_identifier(task_name)
    return (
        f"{var_name} = {class_name}.partial(\n    {partial_params_str},\n"
        f").expand(\n    {expand_params_str},\n)"
    )


def generate_dag_file(dag_name: str, dag_config: dict) -> str:
    """Generate a single Python file containing one DAG."""
    return generate_dags_file({dag_name: dag_config})
