name: build

on:
  push: # Run on pushes to the default branch
    branches: [main]
  pull_request_target: # Also run on pull requests originated from forks
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11', '3.12']
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@master
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        make setup-dev
        make venv
        venv/bin/python3 -m pip install tox-gh-actions
      env:
        SLUGIFY_USES_TEXT_UNIDECODE: yes
    - name: Test with tox
      run: make test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.xml
